import type { Metadata } from "next";
import { Playfair_Display, Rubik, Mulish } from "next/font/google";
import "@/features/site/assets/styles/global.scss";
import { ReactNode } from "react";

const playfairDisplayFont = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair",
});

const rubikFont = Rubik({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-rubik",
});

const mulishFont = Mulish({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${playfairDisplayFont.variable}
          ${rubikFont.variable}
          ${mulishFont.variable}
        `}
      >
        {children}
      </body>
    </html>
  );
}
